name: JS Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
        
    - name: Setup Chromium
      uses: browser-actions/setup-chrome@latest
    - name: Install using Lerna
      run: |
        npm i -g patch-package
        npm install
        npm run lerna bootstrap
        
    - name: Build Starboard Rich Editor
      working-directory: packages/starboard-rich-editor
      run: |
        npm install
        npm run build
        npm pack

    - name: Build Starboard Python
      working-directory: packages/starboard-python
      run: |
        npm install
        npm run build
        npm pack

    - name: Build
      working-directory: packages/starboard-notebook
      run: |
        npm install
        npm run build:nominify

    - name: Test
      working-directory: packages/starboard-notebook
      run: npm test

    - name: Lint
      working-directory: packages/starboard-notebook
      run: npm run lint
      
    - name: Starlit NBTest
      working-directory: packages/starboard-notebook
      run: npm run nbtest -- --timeout 150
